### ISSUE TITLE
add user controls for image treatments

### ISSUE THREAD

**Issue by discoform** [discoform/point-zero#21]
# _data/picture.yml

Jekyll Picture Tag has the following settings fir the theme:
```
presets:
  default:
    markup: auto
    nomarkdown: false
    formats: [original]
    widths: [414, 600, 700, 800, 1127]
    fallback_width: 700
    fallback_format: original
    data_sizes: true
    dimension_attributes: true
    attributes:
      img:  loading="lazy" data-sizes="auto"'
```

Most of these settings should remain for markup and performance reasons, but some users may want to use more images sizes, or fewer. Some may also want to use `.webp` format. 

The following settings can be added to the `config` collection in `admin/config.yml`

- [ ] Make `widths` options selectable
- [ ] Make `.webp` format optional
